const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');

// Try to load Gemini AI
let genAI = null;
try {
    const { GoogleGenerativeAI } = require('@google/generative-ai');
    if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY !== 'your_gemini_api_key_here') {
        genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    }
} catch (e) {
    console.log('Gemini AI not available, AI features will use fallback');
}

// Generate questions using AI
router.post('/generate-questions', auth, async (req, res) => {
    try {
        const { topic, numberOfQuestions = 5, difficulty = 'medium' } = req.body;

        if (!topic) {
            return res.status(400).json({ message: 'Topic is required' });
        }

        if (genAI) {
            const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

            const prompt = `Generate exactly ${numberOfQuestions} multiple choice quiz questions about "${topic}" at ${difficulty} difficulty level.

Return ONLY a valid JSON array with this exact format (no markdown, no code blocks, just pure JSON):
[
  {
    "questionText": "Question here?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correctAnswer": 0
  }
]

Rules:
- correctAnswer is the index (0-3) of the correct option
- Questions should be engaging and educational
- Options should be plausible but only one correct
- No duplicate questions`;

            const result = await model.generateContent(prompt);
            const responseText = result.response.text();

            // Extract JSON from response
            let jsonStr = responseText;
            const jsonMatch = responseText.match(/\[[\s\S]*\]/);
            if (jsonMatch) {
                jsonStr = jsonMatch[0];
            }

            const questions = JSON.parse(jsonStr);

            return res.json({
                message: 'Questions generated by AI ✨',
                questions,
                aiGenerated: true
            });
        }

        // Fallback: generate sample questions without AI
        const fallbackQuestions = generateFallbackQuestions(topic, numberOfQuestions);
        res.json({
            message: 'Sample questions generated (AI not configured)',
            questions: fallbackQuestions,
            aiGenerated: false
        });
    } catch (err) {
        console.error('AI generation error:', err);
        // Fallback
        const { topic, numberOfQuestions = 5 } = req.body;
        const fallbackQuestions = generateFallbackQuestions(topic || 'General', numberOfQuestions);
        res.json({
            message: 'Sample questions generated (AI unavailable)',
            questions: fallbackQuestions,
            aiGenerated: false
        });
    }
});

// Analyze quiz results with AI
router.post('/analyze-results', auth, async (req, res) => {
    try {
        const { quizTitle, participants, totalQuestions } = req.body;

        const avgScore = participants.length > 0
            ? (participants.reduce((sum, p) => sum + p.score, 0) / participants.length).toFixed(1)
            : 0;

        const highestScore = participants.length > 0
            ? Math.max(...participants.map(p => p.score))
            : 0;

        const lowestScore = participants.length > 0
            ? Math.min(...participants.map(p => p.score))
            : 0;

        const completionRate = participants.length > 0
            ? Math.round((participants.filter(p => p.completed).length / participants.length) * 100)
            : 0;

        if (genAI && participants.length > 0) {
            const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

            const prompt = `Analyze these quiz results and give a brief, fun, encouraging summary (3-4 sentences max):
Quiz: "${quizTitle}"
Total Participants: ${participants.length}
Average Score: ${avgScore}/${totalQuestions}
Highest Score: ${highestScore}/${totalQuestions}
Lowest Score: ${lowestScore}/${totalQuestions}
Completion Rate: ${completionRate}%

Be friendly, use emojis, and provide one actionable insight.`;

            const result = await model.generateContent(prompt);
            const analysis = result.response.text();

            return res.json({
                analysis,
                stats: { avgScore, highestScore, lowestScore, completionRate, totalParticipants: participants.length },
                aiGenerated: true
            });
        }

        // Fallback analysis
        let analysis = `📊 Quiz Summary for "${quizTitle}"\n\n`;
        analysis += `👥 ${participants.length} participant(s) took this quiz.\n`;
        analysis += `📈 Average Score: ${avgScore}/${totalQuestions}\n`;
        analysis += `🏆 Highest Score: ${highestScore}/${totalQuestions}\n`;
        analysis += `📉 Lowest Score: ${lowestScore}/${totalQuestions}\n`;
        analysis += `✅ Completion Rate: ${completionRate}%\n\n`;

        if (parseFloat(avgScore) >= totalQuestions * 0.7) {
            analysis += `🎉 Great job everyone! The quiz went really well!`;
        } else if (parseFloat(avgScore) >= totalQuestions * 0.4) {
            analysis += `💪 Good effort! There's room for improvement - keep learning!`;
        } else {
            analysis += `📚 This was a tough one! Consider reviewing the topics and trying again!`;
        }

        res.json({
            analysis,
            stats: { avgScore, highestScore, lowestScore, completionRate, totalParticipants: participants.length },
            aiGenerated: false
        });
    } catch (err) {
        res.status(500).json({ message: 'Analysis error', error: err.message });
    }
});

function generateFallbackQuestions(topic, count) {
    const questions = [];
    for (let i = 1; i <= count; i++) {
        questions.push({
            questionText: `Sample Question ${i} about ${topic}?`,
            options: [
                `${topic} Answer A`,
                `${topic} Answer B`,
                `${topic} Answer C`,
                `${topic} Answer D`
            ],
            correctAnswer: 0
        });
    }
    return questions;
}

module.exports = router;
